### ISSUE TITLE
What's wrong with mp3?

### ISSUE THREAD

**Issue by PAXMA** [PNRxA/corrupted-media-scanner#16]
I've used this scanner to scan my entire SD card (copied everything from SD to my PC and scanned). Error log is very strange, it can't recognize mp3, zip, apk and pdf. What's wrong?

[error201904100725.log](https://github.com/PNRxA/corrupted-media-scanner/files/3064670/error201904100725.log)
[good201904100725.log](https://github.com/PNRxA/corrupted-media-scanner/files/3064671/good201904100725.log)

P.S. right now I am trying to solve a problem with MediaScannerService battery drain on my android 8.1 phone. Thank you for this scanner, it really helps!

**Comment by PNRxA** [comment]
The scanners intended purpose is to detect issues with video files. It uses handbrake to do this.

I'm not too sure if handbrake would be able to detect issues with audio files but that's not the intended purpose of this scanner
